import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

function useJson(path){const [s,setS]=useState({loading:true,error:'',data:null});useEffect(()=>{fetch(path,{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error(`${path} returned ${r.status}`);return r.json()}).then(data=>setS({loading:false,error:'',data})).catch(e=>setS({loading:false,error:e.message,data:null}))},[path]);return s}
const fmt=v=>{if(!v)return'Not yet';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})};
const daysAgo=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?Infinity:(Date.now()-d.getTime())/86400000};
const priority=a=>a.priority||((a.uk_relevant&&(a.relevance_score||0)>=10)?'High':(a.uk_relevant||(a.relevance_score||0)>=8)?'Medium':'Watch');
const csvEscape=v=>'"'+String(v??'').replaceAll('"','""')+'"';
function download(name,text,type='text/plain'){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function useFeedback(){const key='aihm_feedback_v1';const [rows,setRows]=useState(()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}});const add=(item,label)=>{const r={ts:new Date().toISOString(),id:item.id,title:item.title,category:item.category,label,url:item.url};const next=[r,...rows].slice(0,500);setRows(next);localStorage.setItem(key,JSON.stringify(next))};const exportCsv=()=>download('aihm-feedback.csv',['ts,id,label,category,title,url',...rows.map(r=>[r.ts,r.id,r.label,r.category,r.title,r.url].map(csvEscape).join(','))].join('\n'),'text/csv');return{rows,add,exportCsv}}
function App(){
 const news=useJson('./news_data.json'); const cats=useJson('./harm_categories.json'); const fb=useFeedback();
 const articles=Array.isArray(news.data?.articles)?news.data.articles:[]; const clusters=Array.isArray(news.data?.clusters)?news.data.clusters:[]; const briefing=news.data?.briefing||{}; const watchlist=Array.isArray(news.data?.watchlist)?news.data.watchlist:[];
 const [view,setView]=useState('Briefing'); const [category,setCategory]=useState('All'); const [range,setRange]=useState('30'); const [sort,setSort]=useState('Newest first'); const [q,setQ]=useState(''); const [onlyUk,setOnlyUk]=useState(false); const [watch,setWatch]=useState('All');
 const categories=Object.keys(cats.data||{});
 const filtered=useMemo(()=>{const max=range==='All'?Infinity:Number(range);let rows=articles.filter(a=>{if(category!=='All'&&a.category!==category)return false;if(onlyUk&&!a.uk_relevant)return false;if(daysAgo(a.publishedAt)>max)return false;if(watch!=='All'&&!((a.watchlist_hits||[]).some(h=>h.name===watch)))return false;const blob=`${a.title} ${a.summary} ${a.category} ${a.domain} ${a.source} ${(a.why||[]).join(' ')} ${(a.watchlist_hits||[]).map(h=>h.name).join(' ')}`.toLowerCase();return !q||blob.includes(q.toLowerCase())});rows=[...rows].sort((a,b)=>{if(sort==='Oldest first')return new Date(a.publishedAt)-new Date(b.publishedAt);if(sort==='Highest score')return(b.relevance_score||0)-(a.relevance_score||0);if(sort==='Priority'){const r={High:3,Medium:2,Watch:1};return(r[priority(b)]-r[priority(a)])||((b.relevance_score||0)-(a.relevance_score||0))}return new Date(b.publishedAt)-new Date(a.publishedAt)});return rows},[articles,category,range,sort,q,onlyUk,watch]);
 const evidenceTitle = q || watch !== 'All' ? (q || watch) : 'selected filters';
 const exportMarkdown=()=>{const lines=[`# AIHM evidence pack: ${evidenceTitle}`,`Generated: ${new Date().toLocaleString('en-GB')}`,`Items: ${filtered.length}`,'',...filtered.slice(0,50).map((a,i)=>`## ${i+1}. ${a.title}\n- Category: ${a.category}\n- Priority: ${priority(a)} | Score: ${a.relevance_score ?? ''} | UK-relevant: ${a.uk_relevant?'Yes':'No'}\n- Source: ${a.source||a.domain||''} | Date: ${fmt(a.publishedAt)}\n- Why included: ${(a.why||[]).join(', ')}\n- Link: ${a.url||''}\n`)];download('aihm-evidence-pack.md',lines.join('\n'))};
 const exportCsv=()=>download('aihm-results.csv',['title,category,priority,score,uk_relevant,published,source,url,why,semantic_category,semantic_score,semantic_mode',...filtered.map(a=>[a.title,a.category,priority(a),a.relevance_score,a.uk_relevant,a.publishedAt,a.source||a.domain,a.url,(a.why||[]).join('; '),a.semantic_category,a.semantic_score,a.semantic_mode].map(csvEscape).join(','))].join('\n'),'text/csv');
 const Card=({a})=><article className="card"><div className="badges"><span className={`pill ${priority(a).toLowerCase()}`}>{priority(a)}</span>{a.uk_relevant&&<span className="pill uk">UK</span>}{(a.watchlist_hits||[]).map(h=><span key={h.name} className="pill watchhit">{h.name}</span>)}<span className="score">Score {a.relevance_score}</span></div><p className="cat">{a.category}</p><h3>{a.title}</h3>{a.summary&&<p className="summary">{a.summary}</p>}<p className="meta">{a.source||a.domain} · {fmt(a.publishedAt)}</p>{a.semantic_score!==undefined&&<p className="why">Semantic (approx): {a.semantic_category} ({a.semantic_score}) · {a.semantic_mode}</p>}{a.why?.length>0&&<p className="why">Why included: {a.why.join(', ')}</p>}<div className="actions"><a href={a.url} target="_blank" rel="noreferrer">Open</a><button onClick={()=>fb.add(a,'Useful')}>Useful</button><button onClick={()=>fb.add(a,'Not relevant')}>Not relevant</button><button onClick={()=>fb.add(a,'Wrong category')}>Wrong category</button></div></article>;
 return <main className="app"><header className="hero"><div><p className="eyebrow">AIHM horizon scan · free semantic prototype</p><h1>AI Harms Monitor</h1><p>Evidence discovery for AI-enabled harms, open-source/model risks, and specific tools (e.g. Grok). Semantic scoring here is an approximate, local method (no paid API).</p></div><div className="heroBox"><b>{filtered.length}</b><span>shown</span></div></header>
 <section className="nav"><button onClick={()=>setView('Briefing')} className={view==='Briefing'?'active':''}>Briefing</button><button onClick={()=>setView('Evidence')} className={view==='Evidence'?'active':''}>Evidence finder</button><button onClick={()=>setView('Clusters')} className={view==='Clusters'?'active':''}>Trend clusters</button><button onClick={()=>setView('Watchlist')} className={view==='Watchlist'?'active':''}>Model/tool watchlist</button><button onClick={()=>setView('Feedback')} className={view==='Feedback'?'active':''}>Feedback</button><button onClick={()=>setView('Diagnostics')} className={view==='Diagnostics'?'active':''}>Diagnostics</button></section>
 <section className="filters"><label>Search evidence<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Try: Grok, open source, agentic AI, fraud, voice cloning…" /></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Watchlist<select value={watch} onChange={e=>setWatch(e.target.value)}><option>All</option>{watchlist.map(w=><option key={w.name}>{w.name}</option>)}</select></label><label>Time<select value={range} onChange={e=>setRange(e.target.value)}><option value="7">Last week</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="All">All stored</option></select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option>Newest first</option><option>Oldest first</option><option>Priority</option><option>Highest score</option></select></label><label className="check"><input type="checkbox" checked={onlyUk} onChange={e=>setOnlyUk(e.target.checked)} /> UK only</label></section>
 <section className="quick"><button onClick={()=>{setQ('');setWatch('Open-source / open-weight models');setView('Evidence')}}>Evidence: open source</button><button onClick={()=>{setQ('Grok');setWatch('Grok');setView('Evidence')}}>Evidence: Grok</button><button onClick={()=>{setWatch('AI agents');setQ('');setView('Evidence')}}>Evidence: AI agents</button><button onClick={exportMarkdown}>Export evidence pack</button><button onClick={exportCsv}>Export CSV</button></section>
 {news.error&&<p className="error">Could not load data: {news.error}</p>}{news.loading&&<p className="notice">Loading…</p>}
 {view==='Briefing'&&<section className="panel"><h2>Automated briefing summary</h2><p className="headline">{briefing.headline||'No briefing generated yet.'}</p><div className="grid"><div><h3>Top categories</h3><ul>{(briefing.top_categories||[]).map(([k,v])=><li key={k}>{k}: <b>{v}</b></li>)}</ul></div><div><h3>Watchlist hits</h3><ul>{(briefing.top_watchlist_hits||[]).map(([k,v])=><li key={k}>{k}: <b>{v}</b></li>)}</ul></div><div><h3>Top clusters</h3><ul>{(briefing.top_clusters||[]).map(c=><li key={c.id}>{c.title} <b>({c.count})</b></li>)}</ul></div></div><h3>Highest-priority items</h3><div className="cards">{(briefing.highest_priority_items||[]).map((x,i)=><article className="mini" key={i}><b>{x.title}</b><p>{x.category} · {x.priority} · Score {x.score}</p>{x.url&&<a href={x.url} target="_blank" rel="noreferrer">Open</a>}</article>)}</div><p className="note">{briefing.suggested_use}</p></section>}
 {view==='Evidence'&&<section><h2>Evidence finder</h2><p className="note">Use this for quick evidence packs (open source, Grok, agents, etc.). Semantic scores are approximate until you add a paid embedding API.</p><div className="cards">{filtered.map(a=><Card key={a.id} a={a}/>)}</div></section>}
 {view==='Clusters'&&<section className="panel"><h2>Trend clusters</h2><div className="clusterList">{clusters.map(c=><article className="cluster" key={c.id}><h3>{c.title}</h3><p>{c.count} items · {c.uk_count} UK-relevant · highest score {c.highest_score} · latest {fmt(c.latest)}</p><ul>{(c.top_titles||[]).map(t=><li key={t}>{t}</li>)}</ul><button onClick={()=>{setQ(c.title.replace(/^.*?: /,''));setView('Evidence')}}>View matching evidence</button></article>)}</div></section>}
 {view==='Watchlist'&&<section className="panel"><h2>Model/tool watchlist</h2><div className="cards">{watchlist.map(w=><article className="mini" key={w.name}><h3>{w.name}</h3><p>{w.reason}</p><p><b>Aliases:</b> {(w.aliases||[]).join(', ')}</p><p><b>Owner hint:</b> {w.owner_hint}</p><button onClick={()=>{setWatch(w.name);setView('Evidence')}}>View evidence</button></article>)}</div></section>}
 {view==='Feedback'&&<section className="panel"><h2>Feedback capture</h2><p className="note">Feedback is stored in this browser only. Export and share it if needed.</p><button onClick={fb.exportCsv}>Export feedback CSV</button><ul>{fb.rows.map((r,i)=><li key={i}>{r.ts}: {r.label} — {r.title}</li>)}</ul></section>}
 {view==='Diagnostics'&&<section className="panel"><h2>Diagnostics</h2><pre>{JSON.stringify(news.data?.meta||{},null,2)}</pre></section>}
 </main>}
createRoot(document.getElementById('root')).render(<App/>);
